# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SO0t1b9-fnyzk4Okii2mjF2Zn7sVL4vj

###Calculadora
"""

nome = input("Digite seu nome: ")
print("Ola", nome)

num1 = input("Digite o primeiro numero")
operacao = input("Escolha a operação: + - / *")

num2 = input("Digite o segundo numero ")


if num1.isnumeric() and num2.isnumeric():
    num1 = int(num1)
    num2 = int(num2)

    if operacao == "+":
       soma = int(num1) + int(num2)
       print("O resultado da operação é:", soma)

    elif operacao == "-":
       subtracao = int(num1) - int(num2)
       print("O resultado da operação é:", subtracao)

    elif operacao == "/":
       divisao = int(num1) / int(num2)
       print("O resultado da operação é:", divisao)

    elif operacao == "*":
       multiplicacao = int(num1) * int(num2)
       print("O resultado da operação é:", multiplicacao)

    else:
       print("Operação não valida")


else:
    print("Entrada inválida. Por favor, digite números válidos.")